language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - '7' # or '7.0'
  - hhvm


matrix:
  fast_finish: true
#  allow_failures:
#    - php: 'hhvm'

# cache vendor dirs
#cache:
#  directories:
#    - vendor
#    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.0"

  - travis_retry composer install --dev --prefer-dist --no-interaction
  # codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"

before_script:
  - export VENDOR_DIR="~/build/nkostadinov/yii2-user/vendor"
  - mysql -e 'create database user_test;'
  - php tests/_app/yii migrate/up --interactive=0
  - php tests/_app/yii migrate/up --migrationPath=@nkostadinov/user/migrations/advanced --interactive=0
  - ~/.composer/vendor/bin/codecept build
script:
#  - php -S localhost:8080 > /dev/null 2>&1 &
  - ~/.composer/vendor/bin/codecept run

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
